# Generated by Django 5.1.6 on 2025-02-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_meta', '0002_image_delete_imageuploadcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
